credentials:
  usernames:
    admin:
      name: 管理員
      password: $2b$12$ayMiJNk0r1vBS0IKZbXimeJ8Vbd4WLnZKgutFYHNwUIAzWYlTQVAG # admin
      first_time: false
    jackchiu:
      name: Jack Chiu
      password: $2b$12$djDfIFqSvISU9hq1yYD88uTqaG6fVOLt5B8moCpmj89QCZB10fvb6 # superuserjack556
      first_time: false
cookie:
  expiry_days: 0
  key: pass$123@456!789jack000
  name: weather_app_cookies
