credentials:
  usernames:
    admin:
      name: demo_user
      password: password_after_hashing
      first_time: false
cookie:
  expiry_days: 0
  key: key-for-weather-information-promotion-project
  name: weather_app_cookies
