credentials:
  usernames:
    admin:
      name: demo_user
      password: $2b$12$ayMiJNk0r1vBS0IKZbXimeJ8Vbd4WLnZKgutFYHNwUIAzWYlTQVAG
      first_time: false
cookie:
  expiry_days: 0
  key: key-for-weather-information-promotion-project
  name: weather_app_cookies
